// NGUOINHAN
export const SET_INFO_NHAN = "GET_INFO_NHAN";
export const CLEAR_INFO_NHAN = "CLEAR_INFO_NHAN";
export const SET_XY_NHAN = "GET_XY_NHAN";
// CART 
export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const DELETE_ITEM_CART = "DELETE_ITEM_CART";
export const GET_ITEM_CART = "GET_ITEM_CART";
export const GET_ITEM_CART_ERROR = "GET_ITEM_CART_ERROR";
export const INCR_ITEM_CART = "INCR_ITEM_CART";
export const CALCULATE_TONGTIEN = "CALCULATE_TONGTIEN";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT"
// USER
export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_USERS_FAIL= "GET_USERS_FAIL";
export const GET_USER_FAIL= "GET_USER_FAIL";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const USERS_LOADING = "USERS_LOADING";
export const GET_USERS_COUNT = "GET_USERS_COUNT"
export const SAVE_ORDER = "SAVE_ORDER"
export const SAVE_ORDER_FAIL = "SAVE_ORDER_FAIL"
export const LOAD_USER_ORDERS = "LOAD_USER_ORDERS"
// TOPPING
export const GET_TOPPINGS = "GET_TOPPINGS";
export const GET_TOPPING = "GET_TOPPING";
export const ADD_TOPPING = "ADD_TOPPING";
export const UPDATE_TOPPING = "UPDATE_TOPPING";
export const DELETE_TOPPING = "DELETE_TOPPING";
export const GET_TOPPINGS_FAIL= "GET_TOPPINGS_FAIL";
export const GET_TOPPING_FAIL= "GET_TOPPING_FAIL";
export const ADD_TOPPING_FAIL = "ADD_TOPPING_FAIL";
export const UPDATE_TOPPING_FAIL = "UPDATE_TOPPING_FAIL";
export const DELETE_TOPPING_FAIL = "DELETE_TOPPING_FAIL";
export const TOPPINGS_LOADING = "TOPPINGS_LOADING";
export const GET_TOPPINGS_COUNT = "GET_TOPPINGS_COUNT";
export const ADD_CART_TOPP = "ADD_CART_TOPP";
export const REMOVE_CART_TOPP = "REMOVE_CART_TOPP";
export const CLEAR_CART_TOPPS= "CLEAR_CART_TOPP";
export const CALCULATE_TONGTIEN_TOPP= "CALCULATE_TONGTIEN_TOPP";
// ORDER
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER = "GET_ORDER";
export const ADD_ORDER = "ADD_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const GET_ORDERS_FAIL= "FETCH_ORDERS_ERROR";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const ORDERS_LOADING = "ORDERS_LOADING";
export const GET_ORDERS_COUNT = "GET_ORDERS_COUNT";
export const GET_ORDERS_COUNTC = "GET_ORDERS_COUNTC";
export const GET_ORDER_CHART_DATA= "GET_ORDER_CHART_DATA";
// AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_ SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// PRODUCT
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCTS_FAIL= "GET_PRODUCTS_FAIL";
export const GET_PRODUCT_FAIL= "GET_PRODUCT_FAIL";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const GET_PRODUCTS_COUNT = "GET_PRODUCTS_COUNT"

//PROMO
export const GET_PROMOS ="GET_PROMOS";
export const GET_PROMOS_FAIL ="GET_PROMOS_FAIL";
export const GET_PROMO ="GET_PROMO";
export const GET_PROMO_FAIL ="GET_PROMO_FAIL";
export const ADD_PROMO ="ADD_PROMO";
export const UPDATE_PROMO ="UPDATE_PROMO";
export const DELETE_PROMO ="DELETE_PROMO";
export const PROMOS_LOADING ="PROMOS_LOADING";


// TEST
export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM"